Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12
