language: ruby
rvm:
- 2.2
before_install:
- gem update bundler
install:
- bundle install
- gem install rubocop
script: rubocop *
notifications:
  slack:
    secure: G+0tG7O1JixTV56AnzBYw+ICgiLVgGTpD+EHrEvaLiBR660BkIrsR4XfHyg6hy+sEQU2n2je28kIfO7oGYVvjPQsksKV+eNM84Xo+5x4cX3MOByVRGZzN+Vq0ISe1/z4QR+mZO4lBsPPQRy4/O2w2ewzZw/fMb/Ij4WVYq32sHlhtixF2SfLF+gQBdoB8kiR1chFu4bDqN0vZNTXC3HAtdisoUdhQ/VHExNmHCTls1i7Wq50zqUpUbAOwBjHpnVP/glYXzJ5LYKtpBKPCmIuroHue5jLnLSTz9qcu++kxdDh/IukUMfNJIYsUofFXvRaEfbdqGY1adQitib3T3sU8/Nf4WRRsOnqcrrLEC4Ffo/QYKjXNgWYPFxKH1bq3SpCTVDRMJXmqjj2lDA393V7Jd9Ijsq4o7lqWzkUyqV6R8osVeDX4sNru+rHamzW9OXZ63s1eh13yGSmNe3/r/nIuGIq41sTLccNoIjfT3UtrzZy2LXqLNkVmZN3sz7jS4dgca5Cwm0tsQBr1PV/+h5LRFMH9d9TnTSDKXQzHryTK1b8Ul2RlxiWBZApO0fv9ZSnPxETAi2qiS82zxMfiiCDtgRrKz7hvfSm/LwldZBYRlOeECwaeDXr11jVwDFFOT2xWI+8qcDO2sgCah2+lGISxjngnyNoqvKl5/mAgC0S7mY=
